import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

import datas from "../data.json";

import Jobcard from "../components/Jobcard";
import FilterContainer from "../components/FilterContainer";

import { useContext, useEffect, useState } from "react";
import { AppContext } from "../context/state"

export default function Home() {

  const { rules, setRules, click } = useContext(AppContext)

  // const firstArr = rules[0]
  // const secondArr = rules[1]
  const thirdArr = rules[2]

  // console.log(click.filter(data => data == "rule").length)

  let count = 0;
  const ruleCount = click.filter(data => data == "rule").length

  console.log(click)

  function checkReq(data) {
    // check role first
    if (click.includes("role") && click.indexOf("role") == 0) {
      //  if next to role is level
      if (click.includes("level")) {
        // if next to level is rule
        if (click.includes("rule")) {

          while (count < ruleCount) {
            count++
          }

          if (data.role == rules[0] && data.level == rules[1] && data.languages.includes(rules[1 + count])) {
            return data
          }

          // // const func = () => { data.languages.include(rules[2 + count]) }
          console.log(count)

        }
        // no data next to level
        else if (data.role == rules[0] && data.level == rules[1]) {
          return data
        }
      }
      // no data next to it
      else if (data.role == rules[0]) {
        return data
      }

    }
    // check level first 
    else if (click.includes("level") && click.indexOf("level") == 0) {
      if (click.includes("role")) {
        if (data.level == rules[0] && data.role == rules[1]) {
          return data
        }
      }
      else if (data.level == rules[0]) {
        return data
      }

    }
    // check language first
    else if (click.includes("rule") && click.indexOf("rule") == 0) {
      if (data.languages.includes(rules[0])) {
        return data
      }
    }
    // else if (click.includes("role") && click.includes("level")) {
    //   if (data.role == firstArr && data.level == secondArr) {
    //     return data
    //   }
    // }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.bannerContainer}>
        <img className={styles.deskImg} src="./images/bg-header-desktop.svg" alt="" />
        <img className={styles.mobileImg} src="./images/bg-header-mobile.svg" alt="" />
      </div>
      <FilterContainer />
      <main className={styles.main}>

        <div className={styles.jobsContainer}>
          {/* <Jobcard data={data.id} key={index} />; */}
          {/* <Jobcard /> */}
          {click.length > 0 ? datas.filter(checkReq).map((data, index) => {
            return <Jobcard data={data} key={index} />;
          })
            :
            datas.map((data, index) => {
              return <Jobcard data={data} key={index} />;
            })
          }
          {/* {datas.filter(item => {
            return (
              // if (click.includes("role")) {
              click.includes("role") ? item.role == firstArr : item.level == firstArr
              // }
              // else if (click.includes("level")) {
              //   item.level == firstArr
              // }
              // item.role == firstArr
            )
          }
          ).map((data, index) => {
            return <Jobcard data={data} key={index} />;
          })} */}
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
