import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

import datas from "../data.json";

import Jobcard from "../components/Jobcard";
import FilterContainer from "../components/FilterContainer";

import { useContext, useEffect, useState } from "react";
import { AppContext } from "../context/state"

export default function Home() {

  const { filters } = useContext(AppContext)

  const filterFunction = ({ role, level, languages, tools }) => {
    const tags = [role, level]

    if (tools) {
      tags.push(...tools);
    }
    if (languages) {
      tags.push(...languages);
    }

    return filters.every((filter) => tags.includes(filter))
  }

  const tags = [datas.role, datas.level]

  if (datas.tools) {
    tags.push(...datas.tools);
  }
  if (datas.languages) {
    tags.push(...datas.languages);
  }

  // console.log(filters.every((filter) => tags.includes(filter)))

  const filteredPosition = datas.filter(filterFunction)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.bannerContainer}>
        <img className={styles.deskImg} src="./images/bg-header-desktop.svg" alt="" />
        <img className={styles.mobileImg} src="./images/bg-header-mobile.svg" alt="" />
      </div>
      <FilterContainer />
      <main className={styles.main}>

        <div className={styles.jobsContainer}>
          {filters.length > 0 ? filteredPosition.map((data, index) => {
            return <Jobcard data={data} key={index} />;
          })
            :
            datas.map((data, index) => {
              return <Jobcard data={data} key={index} />;
            })
          }
          {/* {
            datas.map((data, index) => {
              return <Jobcard data={data} key={index} />;
            })
          } */}
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
